#############################################################################
# Generated by PAGE version 4.3
# in conjunction with Tcl version 8.6
#    Jul 14, 2014 04:02:27 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_4_0 .top36.tNo44.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top36.tNo44.pg1 
    set site_4_0 $site_4_1
    set site_4_2 .top36.tNo44.pg2 
    set site_4_0 $site_4_2
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+32+32; update
    wm maxsize $top 1914 1045
    wm minsize $top 160 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 1024x768+395+123; update
    wm maxsize $top 1024 1057
    wm minsize $top 172 12
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    label $top.lab38 \
        -background white -borderwidth 4 -disabledforeground {#a3a3a3} \
        -foreground {#000000} -relief ridge -text Label 
    vTcl:DefineAlias "$top.lab38" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -background white -borderwidth 4 -disabledforeground {#a3a3a3} \
        -foreground {#000000} -relief ridge -text Label 
    vTcl:DefineAlias "$top.lab41" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -background white -disabledforeground {#a3a3a3} -foreground {#000000} \
        -text Label 
    vTcl:DefineAlias "$top.lab43" "Label4" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo44 \
        -width 1024 -height 581 -takefocus {} 
    vTcl:DefineAlias "$top.tNo44" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame .top36.tNo44.pg0 -background #d9d9d9
    $top.tNo44 add .top36.tNo44.pg0 \
        -padding 0 -sticky nsew -state normal -text {Representação Algébrica} \
        -image {} -compound center -underline -1 
    set site_4_0  $top.tNo44.pg0
    frame $site_4_0.fra45 \
        -borderwidth 2 -relief groove -background white -height 595 \
        -width 1105 
    vTcl:DefineAlias "$site_4_0.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.fra45 \
        -in $site_4_0 -x -70 -y -10 -width 1105 -height 595 -anchor nw \
        -bordermode ignore 
    frame .top36.tNo44.pg1 -background #d9d9d9
    $top.tNo44 add .top36.tNo44.pg1 \
        -padding 0 -sticky nsew -state normal -text Gráficos -image {} \
        -compound center -underline -1 
    set site_4_1  $top.tNo44.pg1
    frame $site_4_1.fra46 \
        -borderwidth 2 -relief groove -background white -height 555 \
        -width 1025 
    vTcl:DefineAlias "$site_4_1.fra46" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.fra46 \
        -in $site_4_1 -x 0 -y 0 -width 1025 -height 555 -anchor nw \
        -bordermode ignore 
    frame .top36.tNo44.pg2 -background #d9d9d9
    $top.tNo44 add .top36.tNo44.pg2 \
        -padding 0 -sticky nsew -state normal -text {Log Texto} -image {} \
        -compound center -underline -1 
    set site_4_2  $top.tNo44.pg2
    text $site_4_2.tex47 \
        -background white -font TkTextFont -foreground black -height 554 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 1024 
    .top36.tNo44.pg2.tex47 configure -font TkTextFont
    .top36.tNo44.pg2.tex47 insert end text
    vTcl:DefineAlias "$site_4_2.tex47" "Text1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.tex47 \
        -in $site_4_2 -x 0 -y 0 -width 1024 -height 554 -anchor nw \
        -bordermode ignore 
    label $top.lab37 \
        -activebackground {#f9f9f9} -activeforeground black -background white \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label \
        -width 1002 
    vTcl:DefineAlias "$top.lab37" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 0 -y 70 -width 392 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.lab41 \
        -in $top -x 390 -y 70 -width 632 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.lab43 \
        -in $top -x 0 -y 720 -width 1032 -height 46 -anchor nw \
        -bordermode ignore 
    place $top.tNo44 \
        -in $top -x 0 -y 140 -width 1024 -height 581 -anchor nw \
        -bordermode ignore 
    place $top.lab37 \
        -in $top -x 0 -y 0 -width 1024 -height 70 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

