#############################################################################
# Generated by PAGE version 4.3
# in conjunction with Tcl version 8.6
#    Jul 25, 2014 12:47:20 PM




#############################################################################
## vTcl Code to Load Stock Images


if {![info exist vTcl(sourcing)]} {
#############################################################################
## Procedure:  vTcl:rename

proc ::vTcl:rename {name} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    regsub -all "\\." $name "_" ret
    regsub -all "\\-" $ret "_" ret
    regsub -all " " $ret "_" ret
    regsub -all "/" $ret "__" ret
    regsub -all "::" $ret "__" ret

    return [string tolower $ret]
}

#############################################################################
## Procedure:  vTcl:image:create_new_image

proc ::vTcl:image:create_new_image {filename {description {no description}} {type {}} {data {}}} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    # Does the image already exist?
    if {[info exists ::vTcl(images,files)]} {
        if {[lsearch -exact $::vTcl(images,files) $filename] > -1} { return }
    }
    if {![info exists ::vTcl(sourcing)] && [string length $data] > 0} {
        set object [image create  [vTcl:image:get_creation_type $filename]  -data $data]
    } else {
        # Wait a minute... Does the file actually exist?
        if {! [file exists $filename] } {
            # Try current directory
            set script [file dirname [info script]]
            set filename [file join $script [file tail $filename] ]
        }

        if {![file exists $filename]} {
            set description "file not found!"
            ## will add 'broken image' again when img is fixed, for
            ## now create empty
            set object [image create photo -width 1 -height 1]
        } else {
            set object [image create  [vTcl:image:get_creation_type $filename]  -file $filename]
        }
    }

    set reference [vTcl:rename $filename]
    set ::vTcl(images,$reference,image)       $object
    set ::vTcl(images,$reference,description) $description
    set ::vTcl(images,$reference,type)        $type
    set ::vTcl(images,filename,$object)       $filename

    lappend ::vTcl(images,files) $filename
    lappend ::vTcl(images,$type) $object
    set ::vTcl(imagefile,$object) $filename   ;# Rozen
    # return image name in case caller might want it
    return $object
}

#############################################################################
## Procedure:  vTcl:image:get_image

proc ::vTcl:image:get_image {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    set reference [vTcl:rename $filename]

    # Let's do some checking first
    if {![info exists ::vTcl(images,$reference,image)]} {
        # Well, the path may be wrong; in that case check
        # only the filename instead, without the path.

        set imageTail [file tail $filename]

        foreach oneFile $::vTcl(images,files) {
            if {[file tail $oneFile] == $imageTail} {
                set reference [vTcl:rename $oneFile]
                break
            }
        }
    }
    # Rozen. There follows a hack in case one wants to rerun a tcl
    # file which contains a file name where an image is expected.
    if {![info exists ::vTcl(images,$reference,image)]} {
        set ::vTcl(images,$reference,image)  [vTcl:image:create_new_image $filename]
    }
    return $::vTcl(images,$reference,image)
}

#############################################################################
## Procedure:  vTcl:image:get_creation_type

proc ::vTcl:image:get_creation_type {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    switch [string tolower [file extension $filename]] {
        .ppm -
        .jpg -
        .bmp -
        .gif    {return photo}
        .xbm    {return bitmap}
        default {return photo}
    }
}

foreach img {


            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

}
#############################################################################
## vTcl Code to Load User Images

catch {package require Img}

foreach img {

        {{$[pwd]/Leibniz_im.gif} {user image} user {}}

            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_4_0 .top36.tNo44.pg0 
    set site_4_0 $site_4_0
    set site_4_1 .top36.tNo44.pg1 
    set site_4_0 $site_4_1
    set site_4_2 .top36.tNo44.pg2 
    set site_4_0 $site_4_2
    set site_3_0 $base.m57
    set site_3_0 $base.m57
    set site_3_0 $base.m57
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+130+130; update
    wm maxsize $top 1916 1053
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m57" -background {#ffffff} -highlightbackground {#adced8} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1024x748+459+145; update
    wm maxsize $top 1024 1057
    wm minsize $top 172 12
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "EDO Solver"
    vTcl:DefineAlias "$top" "main_window_edo" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    label $top.lab38 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background white -borderwidth 4 -disabledforeground {#a3a3a3} \
        -font font14 -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor {#000000} -relief ridge \
        -text {Conds  Iniciais     y(t) =                         y'(t) = } 
    vTcl:DefineAlias "$top.lab38" "cond_ini_label" vTcl:WidgetProc "main_window_edo" 1
    label $top.lab41 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background white -borderwidth 4 -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -relief ridge -text {Entrada x(t) =} 
    vTcl:DefineAlias "$top.lab41" "xT_label" vTcl:WidgetProc "main_window_edo" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo44 \
        -width 1024 -height 581 -takefocus {} 
    vTcl:DefineAlias "$top.tNo44" "TNotebook1" vTcl:WidgetProc "main_window_edo" 1
    frame .top36.tNo44.pg0 -background #d9d9d9
    $top.tNo44 add .top36.tNo44.pg0 \
        -padding 0 -sticky nsew -state normal -text {Representação Algébrica} \
        -image {} -compound center -underline -1 
    set site_4_0  $top.tNo44.pg0
    frame $site_4_0.fra45 \
        -borderwidth 2 -relief groove -background white -height 645 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1105 
    vTcl:DefineAlias "$site_4_0.fra45" "frame_latex" vTcl:WidgetProc "main_window_edo" 1
    place $site_4_0.fra45 \
        -in $site_4_0 -x -60 -y -60 -width 1105 -height 645 -anchor nw \
        -bordermode ignore 
    frame .top36.tNo44.pg1 -background #d9d9d9
    $top.tNo44 add .top36.tNo44.pg1 \
        -padding 0 -sticky nsew -state normal -text Gráficos -image {} \
        -compound center -underline -1 
    set site_4_1  $top.tNo44.pg1
    frame $site_4_1.fra46 \
        -borderwidth 2 -relief groove -background white -height 555 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 1025 
    vTcl:DefineAlias "$site_4_1.fra46" "frame_plot" vTcl:WidgetProc "main_window_edo" 1
    place $site_4_1.fra46 \
        -in $site_4_1 -x 0 -y 0 -width 1025 -height 555 -anchor nw \
        -bordermode ignore 
    frame .top36.tNo44.pg2 -background #d9d9d9
    $top.tNo44 add .top36.tNo44.pg2 \
        -padding 0 -sticky nsew -state normal -text {Log Texto} -image {} \
        -compound center -underline -1 
    set site_4_2  $top.tNo44.pg2
    text $site_4_2.tex47 \
        -background white -font TkTextFont -foreground black -height 554 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 1024 
    .top36.tNo44.pg2.tex47 configure -font TkTextFont
    .top36.tNo44.pg2.tex47 insert end text
    vTcl:DefineAlias "$site_4_2.tex47" "saida_log_txt" vTcl:WidgetProc "main_window_edo" 1
    place $site_4_2.tex47 \
        -in $site_4_2 -x 0 -y 0 -width 1024 -height 554 -anchor nw \
        -bordermode ignore 
    label $top.lab37 \
        -activebackground {#f9f9f9} -activeforeground black -background white \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -image [vTcl:image:get_image [file join C:/ Users Michael Desktop Projeto-IC-2014 {Fases Anteriores} GUI_Final Leibniz_im.gif]] \
        -text Label -width 1002 
    vTcl:DefineAlias "$top.lab37" "eq_label" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent49" "in_a5" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent52" "in_a4" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent53 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent53" "in_a3" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent54" "in_a2" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent55 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent55" "in_a1" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent56" "in_a0" vTcl:WidgetProc "main_window_edo" 1
    menu $top.m57 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m57 add cascade \
        -menu "$top.m57.men62" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Idioma 
    set site_3_0 $top.m57
    menu $site_3_0.men62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men62 add radiobutton \
        -value Português -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Português 
    $site_3_0.men62 add radiobutton \
        -value English -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label English 
    $site_3_0.men62 add radiobutton \
        -value Español -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Español 
    $top.m57 add cascade \
        -menu "$top.m57.men63" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Notacao 
    set site_3_0 $top.m57
    menu $site_3_0.men63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men63 add radiobutton \
        -value Leibniz -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Leibniz 
    $site_3_0.men63 add radiobutton \
        -value Lagrange -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Lagrange 
    $site_3_0.men63 add radiobutton \
        -value Heaviside -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Heaviside 
    $site_3_0.men63 add radiobutton \
        -value Euler -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label Euler 
    $top.m57 add cascade \
        -menu "$top.m57.men64" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label DigitosFracionarios 
    set site_3_0 $top.m57
    menu $site_3_0.men64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men64 add radiobutton \
        -value {2 Digitos} -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label {2 Digitos} 
    $site_3_0.men64 add radiobutton \
        -value {3 Digitos} -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label {3 Digitos} 
    $site_3_0.men64 add radiobutton \
        -value {4 Digitos} -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label {4 Digitos} 
    label $top.lab65 \
        -activebackground {#f9f9f9} -activeforeground black -background white \
        -borderwidth 4 -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -relief ridge 
    vTcl:DefineAlias "$top.lab65" "label_menu_plot" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent66 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent66" "in_y0" vTcl:WidgetProc "main_window_edo" 1
    entry $top.ent67 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent67" "in_dy0" vTcl:WidgetProc "main_window_edo" 1
    ttk::entry $top.tEn68 \
        -font font15 -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn68" "in_xT" vTcl:WidgetProc "main_window_edo" 1
    scale $top.sca38 \
        -activebackground {#ffffff} -background {#ffffff} -bigincrement 0.0 \
        -font font12 -foreground {#000000} -from 0.0 \
        -highlightbackground {#cbd8d4} -highlightcolor black \
        -label {t Slider} -orient horizontal -relief ridge -resolution 1.0 \
        -sliderrelief ridge -tickinterval 0.0 -to 100.0 \
        -troughcolor {#d9d9d9} 
    vTcl:DefineAlias "$top.sca38" "TimeSlider" vTcl:WidgetProc "main_window_edo" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 0 -y 70 -width 582 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.lab41 \
        -in $top -x 580 -y 70 -width 442 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.tNo44 \
        -in $top -x 250 -y -20 -width 1024 -height 581 -anchor nw \
        -bordermode ignore 
    place $top.lab37 \
        -in $top -x 0 -y 0 -width 1024 -height 70 -anchor nw \
        -bordermode ignore 
    place $top.ent49 \
        -in $top -x 190 -y 20 -width 34 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.ent52 \
        -in $top -x 360 -y 20 -width 34 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.ent53 \
        -in $top -x 20 -y 20 -width 34 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.ent54 \
        -in $top -x 530 -y 20 -width 34 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.ent55 \
        -in $top -x 690 -y 20 -width 34 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.ent56 \
        -in $top -x 850 -y 20 -width 34 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.lab65 \
        -in $top -x -10 -y 720 -width 1052 -height 46 -anchor nw \
        -bordermode ignore 
    place $top.ent66 \
        -in $top -x 210 -y 90 -width 44 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.ent67 \
        -in $top -x 380 -y 90 -width 44 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.tEn68 \
        -in $top -x 670 -y 80 -width 226 -height 46 -anchor nw \
        -bordermode ignore 
    place $top.sca38 \
        -in $top -x 0 -y 680 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

