#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.3
# In conjunction with Tcl version 8.6
#    Jul 07, 2014 06:10:06 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import v03_2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('EDO_Solver')
    root.geometry('800x600+1808+352')
    w = EDO_Solver (root)
    v03_2_support.init(root, w)
    root.mainloop()

w = None
def create_EDO_Solver (root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('EDO_Solver')
    w.geometry('800x600+1808+352')
    w_win = EDO_Solver (w)
    v03_2_support.init(w, w_win, param)
    return w_win

def destroy_EDO_Solver ():
    global w
    w.destroy()
    w = None


class EDO_Solver:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        master.configure(background=_bgcolor)
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.idiomas = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.idiomas,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Idiomas")
        self.idiomas.add_radiobutton(
                value="EN",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="English")
        self.idiomas.add_radiobutton(
                value="ES",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="Espanol")
        self.idiomas.add_radiobutton(
                value="PT",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="Portuguues")
        self.notacao = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.notacao,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Notacao")
        self.notacao.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="Newton")
        self.notacao.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="Leibniz")
        self.notacao.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="Heavside")
        self.notacao.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="Fisica")
        self.digitos_fracionarios = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.digitos_fracionarios,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Digitos_Fracionarios")
        self.digitos_fracionarios.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="2 Digitos")
        self.digitos_fracionarios.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="3 Digitos")
        self.digitos_fracionarios.add_radiobutton(
                value="NewRadio",
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=v03_2_support.TODO,
                foreground="#000000",
                label="4 Digitos")






if __name__ == '__main__':
    vp_start_gui()



