#############################################################################
# Generated by PAGE version 4.3
# in conjunction with Tcl version 8.6
#    Jul 07, 2014 09:21:37 PM




#############################################################################
## vTcl Code to Load Stock Images


if {![info exist vTcl(sourcing)]} {
#############################################################################
## Procedure:  vTcl:rename

proc ::vTcl:rename {name} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    regsub -all "\\." $name "_" ret
    regsub -all "\\-" $ret "_" ret
    regsub -all " " $ret "_" ret
    regsub -all "/" $ret "__" ret
    regsub -all "::" $ret "__" ret

    return [string tolower $ret]
}

#############################################################################
## Procedure:  vTcl:image:create_new_image

proc ::vTcl:image:create_new_image {filename {description {no description}} {type {}} {data {}}} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.
    # Does the image already exist?
    if {[info exists ::vTcl(images,files)]} {
        if {[lsearch -exact $::vTcl(images,files) $filename] > -1} { return }
    }
    if {![info exists ::vTcl(sourcing)] && [string length $data] > 0} {
        set object [image create  [vTcl:image:get_creation_type $filename]  -data $data]
    } else {
        # Wait a minute... Does the file actually exist?
        if {! [file exists $filename] } {
            # Try current directory
            set script [file dirname [info script]]
            set filename [file join $script [file tail $filename] ]
        }

        if {![file exists $filename]} {
            set description "file not found!"
            ## will add 'broken image' again when img is fixed, for
            ## now create empty
            set object [image create photo -width 1 -height 1]
        } else {
            set object [image create  [vTcl:image:get_creation_type $filename]  -file $filename]
        }
    }

    set reference [vTcl:rename $filename]
    set ::vTcl(images,$reference,image)       $object
    set ::vTcl(images,$reference,description) $description
    set ::vTcl(images,$reference,type)        $type
    set ::vTcl(images,filename,$object)       $filename

    lappend ::vTcl(images,files) $filename
    lappend ::vTcl(images,$type) $object
    set ::vTcl(imagefile,$object) $filename   ;# Rozen
    # return image name in case caller might want it
    return $object
}

#############################################################################
## Procedure:  vTcl:image:get_image

proc ::vTcl:image:get_image {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    set reference [vTcl:rename $filename]

    # Let's do some checking first
    if {![info exists ::vTcl(images,$reference,image)]} {
        # Well, the path may be wrong; in that case check
        # only the filename instead, without the path.

        set imageTail [file tail $filename]

        foreach oneFile $::vTcl(images,files) {
            if {[file tail $oneFile] == $imageTail} {
                set reference [vTcl:rename $oneFile]
                break
            }
        }
    }
    # Rozen. There follows a hack in case one wants to rerun a tcl
    # file which contains a file name where an image is expected.
    if {![info exists ::vTcl(images,$reference,image)]} {
        set ::vTcl(images,$reference,image)  [vTcl:image:create_new_image $filename]
    }
    return $::vTcl(images,$reference,image)
}

#############################################################################
## Procedure:  vTcl:image:get_creation_type

proc ::vTcl:image:get_creation_type {filename} {
    ## This procedure may be used free of restrictions.
    ##    Exception added by Christian Gavin on 08/08/02.
    ## Other packages and widget toolkits have different licensing requirements.
    ##    Please read their license agreements for details.

    switch [string tolower [file extension $filename]] {
        .ppm -
        .jpg -
        .bmp -
        .gif    {return photo}
        .xbm    {return bitmap}
        default {return photo}
    }
}

foreach img {


            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

}
#############################################################################
## vTcl Code to Load User Images

catch {package require Img}

foreach img {

        {{$[pwd]/images/Leibniz_order2_notation.gif} {user image} user {}}

            } {
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Arial -size 16 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_3_0 $base.m37
    set site_3_0 $base.m37
    set site_3_0 $base.m37
    set site_4_0 .top36.tNo64.pg0 
    set site_4_1 .top36.tNo64.pg1 
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+5+27; update
    wm maxsize $top 3200 1058
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m37" -relief sunken -background {#858c8e} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x600+1791+333; update
    wm maxsize $top 3200 1058
    wm minsize $top 72 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm title $top "EDO Solver"
    vTcl:DefineAlias "$top" "edo_main_window" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    menu $top.m37 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#9ebdd8} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m37 add cascade \
        -menu "$top.m37.men50" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Languages 
    set site_3_0 $top.m37
    menu $site_3_0.men50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font menu -foreground black -tearoff 0 
    $site_3_0.men50 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label English 
    $site_3_0.men50 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Portuguese 
    $site_3_0.men50 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Spanish 
    $top.m37 add cascade \
        -menu "$top.m37.men51" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Representation 
    set site_3_0 $top.m37
    menu $site_3_0.men51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font menu -foreground black -tearoff 0 
    $site_3_0.men51 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Leibniz 
    $site_3_0.men51 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Line 
    $site_3_0.men51 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Newton 
    $site_3_0.men51 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label Heavside 
    $top.m37 add cascade \
        -menu "$top.m37.men52" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Decimal 
    set site_3_0 $top.m37
    menu $site_3_0.men52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font menu -foreground black -tearoff 0 
    $site_3_0.men52 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label {2 Digits} 
    $site_3_0.men52 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label {3 Digits} 
    $site_3_0.men52 add radiobutton \
        -variable selectedButton -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -command TODO \
        -font TkMenuFont -foreground {#000000} -label {4 Digits} 
    label $top.lab41 \
        -background {#86a6bf} -font font10 -foreground {#000000} \
        -relief raised \
        -text {Linear Differential Equation with  Constant Coefficients Solver} 
    vTcl:DefineAlias "$top.lab41" "title_label" vTcl:WidgetProc "edo_main_window" 1
    label $top.lab43 \
        -background {#86a6bf} -borderwidth 3 -disabledforeground {#8ba3a1} \
        -foreground {#000000} \
        -image [vTcl:image:get_image [file join / Users Michael Desktop {Projeto IC 2014} Python_GUI_Tutorial v05 images Leibniz_order2_notation.gif]] \
        -relief sunken -text Label 
    vTcl:DefineAlias "$top.lab43" "Label2" vTcl:WidgetProc "edo_main_window" 1
    entry $top.cpd45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.cpd45" "Entry2" vTcl:WidgetProc "edo_main_window" 1
    entry $top.ent48 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent48" "Entry1" vTcl:WidgetProc "edo_main_window" 1
    entry $top.ent49 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent49" "Entry3" vTcl:WidgetProc "edo_main_window" 1
    ttk::label $top.tLa59 \
        -background {#86a6bf} -foreground {#000000} -borderwidth 2 \
        -relief raised -text {Init.Conditions: y'(0) =          y(0) = } 
    vTcl:DefineAlias "$top.tLa59" "TLabel2" vTcl:WidgetProc "edo_main_window" 1
    entry $top.ent60 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent60" "Entry4" vTcl:WidgetProc "edo_main_window" 1
    entry $top.ent61 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent61" "Entry5" vTcl:WidgetProc "edo_main_window" 1
    ttk::label $top.cpd62 \
        -background {#86a6bf} -foreground {#000000} -borderwidth 2 \
        -relief raised -text {Input x(t) = } 
    vTcl:DefineAlias "$top.cpd62" "TLabel3" vTcl:WidgetProc "edo_main_window" 1
    ttk::entry $top.tEn63 \
        -foreground {} -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn63" "TEntry1" vTcl:WidgetProc "edo_main_window" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo64 \
        -width 804 -height 440 -takefocus {} 
    vTcl:DefineAlias "$top.tNo64" "TNotebook1" vTcl:WidgetProc "edo_main_window" 1
    frame .top36.tNo64.pg0 -background #d9d9d9
    $top.tNo64 add .top36.tNo64.pg0 \
        -padding 0 -sticky nsew -state normal -text {Solution Log} -image {} \
        -compound center -underline -1 
    set site_4_0  $top.tNo64.pg0
    frame .top36.tNo64.pg1 -background #d9d9d9
    $top.tNo64 add .top36.tNo64.pg1 \
        -padding 0 -sticky nsew -state normal -text Plot -image {} \
        -compound center -underline -1 
    set site_4_1  $top.tNo64.pg1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab41 \
        -in $top -x 0 -y 0 -width 800 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab43 \
        -in $top -x 0 -y 20 -width 800 -height 112 -anchor nw \
        -bordermode ignore 
    place $top.cpd45 \
        -in $top -x 250 -y 60 -width 52 -height 37 -anchor nw \
        -bordermode inside 
    place $top.ent48 \
        -in $top -x 20 -y 60 -width 52 -height 37 -anchor nw \
        -bordermode ignore 
    place $top.ent49 \
        -in $top -x 490 -y 60 -width 52 -height 37 -anchor nw \
        -bordermode ignore 
    place $top.tLa59 \
        -in $top -x 0 -y 130 -width 272 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.ent60 \
        -in $top -x 150 -y 130 -width 32 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.ent61 \
        -in $top -x 230 -y 130 -width 32 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.cpd62 \
        -in $top -x 270 -y 130 -width 529 -height 30 -anchor nw \
        -bordermode inside 
    place $top.tEn63 \
        -in $top -x 360 -y 130 -width 430 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.tNo64 \
        -in $top -x 0 -y 160 -width 804 -height 440 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

