#! /usr/bin/env python
#
# Support module generated by PAGE version 4.3
# In conjunction with Tcl version 8.6
#    Jul 09, 2014 02:52:30 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global output_selection
    output_selection = StringVar()


def TODO():
        print ('v01_support.TODO')
        sys.stdout.flush()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


