#! /usr/bin/env python
#
# Support module generated by PAGE version 4.3
# In conjunction with Tcl version 8.6
#    Jul 15, 2014 09:58:55 PM


import sys

from Tkinter import *
import ttk



def TODO():
        print ('v5_support.TODO')
        sys.stdout.flush()

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    Popen.terminate()
    Popen.kill()
    top_level = None
    exit(0)


