#############################################################################
# Generated by PAGE version 4.3
# in conjunction with Tcl version 8.6
#    Jul 09, 2014 10:28:12 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+5+27; update
    wm maxsize $top 1280 752
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d4d2d8} 
    wm focusmodel $top passive
    wm geometry $top 800x600+133+81; update
    wm maxsize $top 1280 752
    wm minsize $top 72 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm title $top "EDO Solver"
    vTcl:DefineAlias "$top" "EDO_main_window" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    label $top.lab37 \
        -background {#d9d9d9} -borderwidth 5 -foreground {#000000} \
        -relief ridge -text {Diff Equation Here} -width 800 
    vTcl:DefineAlias "$top.lab37" "EDO_viewer" vTcl:WidgetProc "EDO_main_window" 1
    label $top.lab40 \
        -background {#f7f7f7} -foreground {#000000} -relief ridge \
        -text Init.Conditions 
    vTcl:DefineAlias "$top.lab40" "Label2" vTcl:WidgetProc "EDO_main_window" 1
    label $top.lab41 \
        -background {#ffffff} -foreground {#000000} -relief ridge \
        -text {Input x(t)} 
    vTcl:DefineAlias "$top.lab41" "Label3" vTcl:WidgetProc "EDO_main_window" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab37 \
        -in $top -x 0 -y 0 -width 800 -height 100 -anchor nw \
        -bordermode ignore 
    place $top.lab40 \
        -in $top -x 0 -y 100 -width 310 -height 52 -anchor nw \
        -bordermode ignore 
    place $top.lab41 \
        -in $top -x 310 -y 100 -width 490 -height 52 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

